### ISSUE TITLE
PRrefactoring-lunchmenu

### ISSUE THREAD

**Issue by nlom0218** [nlom0218/teacher_browser#163]
# Refactoring for lunchmenu page

### Basic
- [x] 불필요한 내용 삭제 #164 #165 
- [x] 컴포넌트 분리 #166 #169 
- [x] #175 #177 
   - `state`구조 

### 렌더링 최적화
- [ ] refactoring-lunchmenu-rendering
   -  렌더링에 따른 `useEffect()`훅의 호출 
   - `useContext()` 훅, `useReducer()` 훅의 사용
   - `useCallback()` 훅, `useMemo()` 훅의 사용

### 함수, 변수 리팩토링
- [x] refactoring-lunchmenu-function& variable #188 
   - [x] 변수명 함수명 리팩토링
   - [x] Components/LunchmenuBtn onClickBtn(): 중복되는 내용 제거
   - [x] Components/LunchmenuInfo getMenu(): 적절한 메서드 사용
   - [x] Pages/Lunchmenu processSetDate(): 라이브러리 사용

### 타입스크립트 적용
- [x] refactoring-lunchmenu-typescript #180 

---

## changed files👇👇👇👇👇
- pages/Lunchmenu
- Components/Lunchmenu/**
- Components/Shared/BasicContainer
- Components/Shared/PopupContainer
- Components/Shared/BtnPopupContainer
